// @generated by solverforge-cli: data v1
// Domain-specialized after generation for the synthetic fleet readiness demo.

mod builders;
mod catalog;
mod scenario;
mod solutions;

use std::str::FromStr;

use crate::constraints::support::apply_technician_shortage;
use crate::domain::Plan;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DemoData {
    Small,
    Standard,
    Large,
}

const AVAILABLE_DEMO_DATA: &[DemoData] = &[DemoData::Small, DemoData::Standard, DemoData::Large];
const DEFAULT_DEMO_DATA: DemoData = DemoData::Large;

pub fn default_demo_data() -> DemoData {
    DEFAULT_DEMO_DATA
}

pub fn available_demo_data() -> &'static [DemoData] {
    AVAILABLE_DEMO_DATA
}

impl DemoData {
    pub fn id(self) -> &'static str {
        match self {
            DemoData::Small => "BASELINE",
            DemoData::Standard => "TECHNICIAN_SHORTAGE",
            DemoData::Large => "BASELINE_FULL",
        }
    }

    pub fn default_demo_data() -> Self {
        default_demo_data()
    }

    pub fn available_demo_data() -> &'static [Self] {
        available_demo_data()
    }
}

impl FromStr for DemoData {
    type Err = ();

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_ascii_uppercase().as_str() {
            "SMALL" | "BASELINE" => Ok(DemoData::Small),
            "STANDARD" | "TECHNICIAN_SHORTAGE" => Ok(DemoData::Standard),
            "LARGE" | "BASELINE_FULL" => Ok(DemoData::Large),
            _ => Err(()),
        }
    }
}

pub fn generate(demo: DemoData) -> Plan {
    let mut plan = baseline_plan();
    match demo {
        DemoData::Small | DemoData::Large => {}
        DemoData::Standard => apply_technician_shortage(&mut plan, "ELEC", -1),
    }
    plan
}

pub fn baseline_plan() -> Plan {
    scenario::baseline_plan()
}

pub fn baseline_solution_plan() -> Plan {
    solutions::baseline_solution_plan()
}

pub fn improvable_solve_seed_plan() -> Plan {
    solutions::improvable_solve_seed_plan()
}

pub fn technician_shortage_solution_plan() -> Plan {
    solutions::technician_shortage_solution_plan()
}

pub fn delayed_parts_plan() -> Plan {
    solutions::delayed_parts_plan()
}

pub fn raised_readiness_plan() -> Plan {
    solutions::raised_readiness_plan()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn baseline_full_demo_is_completely_unassigned() {
        let plan = generate(DemoData::Large);

        assert!(plan
            .work_packages
            .iter()
            .all(|package| package.dock_idx.is_none() && package.start_day_idx.is_none()));
        assert!(plan
            .inspection_assignments
            .iter()
            .all(|assignment| assignment.day_idx.is_none()));
        assert!(plan
            .training_assignments
            .iter()
            .all(|assignment| assignment.day_idx.is_none()));
    }

    #[test]
    fn improvable_solve_seed_assigns_all_required_variables() {
        let plan = improvable_solve_seed_plan();

        assert!(plan
            .work_packages
            .iter()
            .all(|package| package.dock_idx.is_some() && package.start_day_idx.is_some()));
        assert!(plan
            .inspection_assignments
            .iter()
            .all(|assignment| assignment.day_idx.is_some()));
        assert!(plan
            .training_assignments
            .iter()
            .all(|assignment| assignment.day_idx.is_some()));
    }
}
