[package]
name = "solverforge-hospital"
version = "1.0.2"
edition = "2021"
rust-version = "1.95"
description = "SolverForge hospital scheduling example"
publish = false

[dependencies]
solverforge = { version = "0.13.1", features = [
  "serde",
  "console",
  "verbose-logging",
] }
solverforge-ui = "0.6.5"
rand = "0.10.1"

axum = "0.8.9"
tokio = { version = "1.52.3", features = ["full"] }
tokio-stream = { version = "0.1.18", features = ["sync"] }
tower-http = { version = "0.6.10", features = ["fs", "cors"] }
tower = "0.5.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
chrono = { version = "0.4.44", features = ["serde"] }
parking_lot = "0.12.5"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
